##############################################################################
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

name: Publish App Fair Catalog

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    runs-on: macos-11
    timeout-minutes: 30

    env:
      DEVELOPER_DIR: /Applications/Xcode_13.0_beta.app/Contents/Developer

    steps:
      - uses: fwal/setup-swift@v1
        with:
          swift-version: '5.5'

      - name: Checkout Fair
        uses: actions/checkout@v2
        with:
          repository: fairapp/Fair.git
          ref: main
          path: fair/

      - name: Checkout Catalog
        uses: actions/checkout@v2
        with:
          repository: appfair/appfair.github.io.git
          ref: main
          path: appfair.github.io/

      - name: Generate catalog
        run: |
          cd fair/
          swift run -- fairtool catalog --verbose true --hub github.com/appfair --token "${{ secrets.APP_FAIR_BOT_TOKEN }}" --artifact-extension "zip" -o ../appfair.github.io/fairapps.json
          swift run -- fairtool catalog --verbose true --hub github.com/appfair --token "${{ secrets.APP_FAIR_BOT_TOKEN }}" --artifact-extension "ipa" -o ../appfair.github.io/fairapps-iOS.json
          cd ..

      - name: Update catalog
        env:
          GITHUB_TOKEN: ${{ secrets.APP_FAIR_BOT_TOKEN }}
        run: |
          cd appfair.github.io/
          git pull # grab any updates that may have snuck in
          git add fairapps.json
          git add fairapps-iOS.json
          git commit -m "catalog update" || echo "nothing to commit"
          git push

