##############################################################################
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

name: Publish App Catalogs

env:
  FAIRTOOL: "fairtool"
  # fairtool-head will build from source, which adds a few minutes
  #FAIRTOOL: "fairtool-head"
  
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    # broken on linux image ubuntu-20.04 version 20220922.2: "command failed with exit code 1 (use -v to see invocation)\n/lib/x86_64-linux-gnu/Scrt1.o:function _start: error: undefined reference to \'__libc_csu_fini\'\n/lib/x86_64-linux-gnu/Scrt1.o:function _start: error: undefined reference to \'__libc_csu_init\'\nclang-13: error: linker command failed with exit code 1 (use -v to see invocation)", diagnosticFile: nil)"
"
    #runs-on: ubuntu-latest

    timeout-minutes: 30
    steps:
      - name: "Install ${{ env.FAIRTOOL }}"
        run: |
          # https://github.com/actions/runner-images/issues/6283
          #eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew --version
          brew install fair-ground/tool/$FAIRTOOL
          $FAIRTOOL version

      - name: Checkout Catalog
        uses: actions/checkout@v2
        with:
          repository: appfair/appfair.github.io.git
          ref: main
          path: appfair.github.io/

      - name: Checkout Casks
        env:
          GITHUB_TOKEN: ${{ secrets.APP_FAIR_BOT_TOKEN }}
        run: |
          git clone https://user:$GITHUB_TOKEN@github.com/appfair/homebrew-app

      - name: Clear Casks
        run: |
          rm -rf homebrew-app/Casks/
          mkdir -p homebrew-app/Casks/
          rm -f fairapps-macos.json fairapps-macos.md
          rm -f fairapps-ios.json fairapps-ios.md

      - name: Setup appfair.github.io repo
        run: |
          cd appfair.github.io/
          git config credential.username "appfairbot"
          git config credential.password "${{ secrets.APP_FAIR_BOT_TOKEN }}"
          git config user.name "appfairbot"
          git config user.email "appfairbot@appfair.net"
          cd -

      - name: "Configure posting auth"
        run: |
          # configure the posting auth just once
          echo "FAIRTOOL_TWITTER_USER=${{ secrets.APP_FAIR_TWITTER_USER }}" >> $GITHUB_ENV
          echo "FAIRTOOL_TWITTER_CONSUMER_KEY=${{ secrets.APP_FAIR_TWITTER_CONSUMER_KEY }}" >> $GITHUB_ENV
          echo "FAIRTOOL_TWITTER_CONSUMER_SECRET=${{ secrets.APP_FAIR_TWITTER_CONSUMER_SECRET }}" >> $GITHUB_ENV
          echo "FAIRTOOL_TWITTER_TOKEN=${{ secrets.APP_FAIR_TWITTER_TOKEN }}" >> $GITHUB_ENV
          echo "FAIRTOOL_TWITTER_TOKEN_SECRET=${{ secrets.APP_FAIR_TWITTER_TOKEN_SECRET }}" >> $GITHUB_ENV

      - name: Generate macOS catalog
        run: |
          cp appfair.github.io/fairapps-macos.json appfair.github.io/fairapps-macos_old.json && touch appfair.github.io/fairapps-macos_old.json
          $FAIRTOOL fair catalog \
            --verbose \
            --hub github.com/appfair \
            --base-repo "App" \
            --funding-sources \
            --token "${{ secrets.APP_FAIR_BOT_TOKEN }}" \
            --catalog-name "Fair Apps" \
            --catalog-identifier "net.appfair.fairapps-macos" \
            --artifact-extension "zip" \
            --fairseal-issuer "appfairbot" \
            --retry-duration 600 \
            --allow-license "${{ secrets.APP_FAIR_ALLOW_LICENSE }}" \
            --allow-name "${{ secrets.APP_FAIR_ALLOW_NAME }}" \
            --deny-name "${{ secrets.APP_FAIR_DENY_NAME }}" \
            --allow-from "${{ secrets.APP_FAIR_ALLOW_FROM }}" \
            --deny-from "${{ secrets.APP_FAIR_DENY_FROM }}" \
            --cask-folder homebrew-app/Casks/ \
            -o appfair.github.io/fairapps-macos.json

          # update the catalog to generate the markdown and news items 
          $FAIRTOOL source postrelease \
            --from-catalog appfair.github.io/fairapps-macos_old.json \
            --to-catalog appfair.github.io/fairapps-macos.json \
            --markdown-index appfair.github.io/fairapps-macos.md \
            --post-url 'https://appfair.app/fair?app=#(appname_hyphenated)' \
            --tweet-body 'New App Release (macOS): #(appname) #(appversion) - https://appfair.app/fair?app=#(appname_hyphenated)' \
            --post-body 'New Release on the App Fair: #(appname) #(appversion) - https://appfair.app/fair?app=#(appname_hyphenated)' \
            --post-title 'New Release: #(appname) #(appversion)' \
            --post-title-update 'New Release: #(appname) #(appversion)' \
            --post-app-id 'app.#(appname_hyphenated)' \
            --post-caption "#(appname) #(appversion) released" \
            --post-caption-update "#(appname) updated from #(oldappversion) to #(appversion)" \
            --news-items 10 \
            -o appfair.github.io/fairapps-macos_new.json

          mv appfair.github.io/fairapps-macos_new.json appfair.github.io/fairapps-macos.json

          cd appfair.github.io/

          git add fairapps-macos.md fairapps-macos.json

          # TODO: deprecate legacy endpoints
          cp fairapps-macos.md fairapps.md
          cp fairapps-macos.json fairapps.json
          git add fairapps.md fairapps.json 

          git pull
          git commit -m "macOS catalog update" || echo "nothing to commit"
          git push
          cd -

      - name: Generate iOS catalog
        run: |
          cp appfair.github.io/fairapps-ios.json appfair.github.io/fairapps-ios_old.json && touch appfair.github.io/appcasks_old.json
          $FAIRTOOL fair catalog \
            --verbose \
            --hub github.com/appfair \
            --base-repo "App" \
            --funding-sources \
            --token "${{ secrets.APP_FAIR_BOT_TOKEN }}" \
            --catalog-name "Fair Apps (iOS)" \
            --catalog-identifier "net.appfair.fairapps-ios" \
            --artifact-extension "ipa" \
            --fairseal-issuer "appfairbot" \
            --retry-duration 600 \
            --allow-license "${{ secrets.APP_FAIR_ALLOW_LICENSE }}" \
            --allow-name "${{ secrets.APP_FAIR_ALLOW_NAME }}" \
            --deny-name "${{ secrets.APP_FAIR_DENY_NAME }}" \
            --allow-from "${{ secrets.APP_FAIR_ALLOW_FROM }}" \
            --deny-from "${{ secrets.APP_FAIR_DENY_FROM }}" \
            -o appfair.github.io/fairapps-ios.json

          # generate AltStore-specific catalog
          cd appfair.github.io/
          cat fairapps-ios.json | jq '.apps |= map(select(.bundleIdentifier|match("${{ secrets.APP_FAIR_ALTSTORE_APPS }}")))' | jq '.sourceURL |= "https://www.appfair.net/fairapps-altstore.json"' > fairapps-altstore.json

          cd -

          # update the catalog to generate the markdown and news items 
          $FAIRTOOL source postrelease \
            --from-catalog appfair.github.io/fairapps-ios_old.json \
            --to-catalog appfair.github.io/fairapps-ios.json \
            --markdown-index appfair.github.io/fairapps-ios.md \
            --post-url 'https://appfair.app/fair?app=#(appname_hyphenated)' \
            --post-body 'New Release on the App Fair: #(appname) #(appversion) - https://appfair.app/fair?app=#(appname_hyphenated)' \
            --post-title 'New Release: #(appname) #(appversion)' \
            --post-title-update 'New Release: #(appname) #(appversion)' \
            --post-app-id 'app.#(appname_hyphenated)' \
            --post-caption "#(appname) #(appversion) released" \
            --post-caption-update "#(appname) updated from #(oldappversion) to #(appversion)" \
            --news-items 0 \
            -o appfair.github.io/fairapps-ios_new.json

          mv appfair.github.io/fairapps-ios_new.json appfair.github.io/fairapps-ios.json

          cd appfair.github.io/
          git add fairapps-ios.md fairapps-ios.json fairapps-altstore.json
          git pull
          git commit -m "iOS catalog update" || echo "nothing to commit"
          git push
          cd -

      - name: Generate appcasks catalog
        run: |
          cp appfair.github.io/appcasks.json appfair.github.io/appcasks_old.json && touch appfair.github.io/appcasks_old.json
          $FAIRTOOL brew appcasks \
            --verbose \
            --hub github.com/appfair \
            --base-repo "App" \
            --starrer-name "appfairbot" \
            --topic-name "appfair-cask" \
            --casks-repo "appcasks" \
            --max-apps 1000000 \
            --funding-sources \
            --token "${{ secrets.APP_FAIR_BOT_TOKEN }}" \
            --catalog-name "Homebrew Casks" \
            --catalog-identifier "net.appfair.appcasks" \
            --merge-cask-info "https://formulae.brew.sh/api/cask.json" \
            --merge-cask-stats "https://formulae.brew.sh/api/analytics/cask-install/homebrew-cask/30d.json" \
            --boost-apps "${{ secrets.APP_FAIR_BOOSTED_CASKS }}" \
            --boost-factor 100000 \
            --retry-duration 600 \
            -o appfair.github.io/appcasks.json

          # update the catalog to generate the markdown and news items 
          $FAIRTOOL source postrelease \
            --from-catalog appfair.github.io/appcasks_old.json \
            --to-catalog appfair.github.io/appcasks.json \
            --markdown-index appfair.github.io/appcasks.md \
            --post-url 'https://appfair.app/fair?cask=#(apptoken)' \
            --tweet-body 'New App Release (macOS): #(appname) #(appversion) - https://appfair.app/fair?cask=#(apptoken)' \
            --post-body 'New Release on the App Fair: #(appname) #(appversion) - https://appfair.app/fair?cask=#(apptoken)' \
            --post-title 'New Release: #(appname) #(appversion)' \
            --post-title-update 'New Release: #(appname) #(appversion)' \
            --post-app-id '#(apptoken)' \
            --post-caption "#(appname) #(appversion) released" \
            --post-caption-update "#(appname) updated from #(oldappversion) to #(appversion)" \
            --update-version-date \
            --news-items 100 \
            -o appfair.github.io/appcasks_new.json

          mv appfair.github.io/appcasks_new.json appfair.github.io/appcasks.json

          cd appfair.github.io/
          git add appcasks.json appcasks.md
          git pull
          git commit -m "casks catalog update" || echo "nothing to commit"
          git push

      - name: Update casks inventory
        run: |
          cd homebrew-app/
          git config user.name "appfairbot"
          git config user.email "appfairbot@appfair.net"
          git pull
          git add .
          git commit -m "cask update" || echo "nothing to commit"
          git push
          cd -

