##############################################################################
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

name: Publish App Fair Catalog

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Install fairtool
        run: brew install appfair/app/fairtool

      - name: Checkout Catalog
        uses: actions/checkout@v2
        with:
          repository: appfair/appfair.github.io.git
          ref: main
          path: appfair.github.io/

      - name: Checkout Casks
        env:
          GITHUB_TOKEN: ${{ secrets.APP_FAIR_BOT_TOKEN }}
        run: |
          git clone https://user:$GITHUB_TOKEN@github.com/appfair/homebrew-app

      - name: Clear Casks
        run: |
          rm -rf homebrew-app/Casks/
          mkdir -p homebrew-app/Casks/
          rm -f fairapps-macos.json fairapps-macos.md
          rm -f fairapps-ios.json fairapps-ios.md

      - name: Generate macOS catalog
        run: |
          fairtool catalog \
            --verbose true \
            --hub github.com/appfair \
            --token "${{ secrets.APP_FAIR_BOT_TOKEN }}" \
            --artifact-extension "zip" \
            --fairseal-issuer "appfairbot" \
            --retry-duration 600 \
            --allow-license "${{ secrets.APP_FAIR_ALLOW_LICENSE }}" \
            --allow-name "${{ secrets.APP_FAIR_ALLOW_NAME }}" \
            --deny-name "${{ secrets.APP_FAIR_DENY_NAME }}" \
            --allow-from "${{ secrets.APP_FAIR_ALLOW_FROM }}" \
            --deny-from "${{ secrets.APP_FAIR_DENY_FROM }}" \
            --cask-folder homebrew-app/Casks/ \
            --index appfair.github.io/fairapps-macos.md \
            -o appfair.github.io/fairapps-macos.json

      - name: Generate iOS catalog
        run: |
          fairtool catalog \
            --verbose true \
            --hub github.com/appfair \
            --token "${{ secrets.APP_FAIR_BOT_TOKEN }}" \
            --artifact-extension "ipa" \
            --fairseal-issuer "appfairbot" \
            --retry-duration 600 \
            --allow-license "${{ secrets.APP_FAIR_ALLOW_LICENSE }}" \
            --allow-name "${{ secrets.APP_FAIR_ALLOW_NAME }}" \
            --deny-name "${{ secrets.APP_FAIR_DENY_NAME }}" \
            --allow-from "${{ secrets.APP_FAIR_ALLOW_FROM }}" \
            --deny-from "${{ secrets.APP_FAIR_DENY_FROM }}" \
            --index appfair.github.io/fairapps-ios.md \
            -o appfair.github.io/fairapps-ios.json


          # generate AltStore-specific catalog
          cd appfair.github.io
          cat fairapps-ios.json | jq '.apps |= map(select(.bundleIdentifier|match("${{ secrets.APP_FAIR_ALTSTORE_APPS }}")))' | jq '.sourceURL |= "https://www.appfair.net/fairapps-altstore.json"' > fairapps-altstore.json

          cd -

      - name: Generate appcasks catalog
        run: |
          fairtool appcasks \
            --verbose true \
            --hub github.com/appfair \
            --token "${{ secrets.APP_FAIR_BOT_TOKEN }}" \
            --boost-factor 100000 \
            --retry-duration 600 \
            -o appfair.github.io/appcasks.json

      - name: Commit catalog
        run: |
          cd appfair.github.io/
          git config credential.username "appfairbot"
          git config credential.password "${{ secrets.APP_FAIR_BOT_TOKEN }}"
          git config user.name "appfairbot"
          git config user.email "appfairbot@appfair.net"
          cp fairapps-macos.md fairapps.md
          cp fairapps-macos.json fairapps.json
          git add fairapps.md
          git add fairapps.json
          git add fairapps-macos.md
          git add fairapps-macos.json
          git add fairapps-ios.md
          git add fairapps-ios.json
          git add fairapps-altstore.json
          git add appcasks.json
          git pull
          git commit -m "catalog update" || echo "nothing to commit"
          git push

      - name: Update casks inventory
        run: |
          cd homebrew-app/
          git config user.name "appfairbot"
          git config user.email "appfairbot@appfair.net"
          git pull
          git add .
          git commit -m "cask update" || echo "nothing to commit"
          git push

