##############################################################################
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

name: Publish App Fair Catalog

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Test Cask Update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://user:$GITHUB_TOKEN@github.com/appfair/homebrew-apps 

          cd homebrew-apps
          git config user.name "appfairbot"
          git config user.email "appfairbot@appfair.net"

          echo '' >> README.md
          git add README.md
          git commit -m "ci: test commit"
          git remote -v # Prints:
          git push


      - name: Checkout Fair
        uses: actions/checkout@v2
        with:
          repository: fairapp/Fair.git
          ref: main
          path: fair/

      - name: Checkout Catalog
        uses: actions/checkout@v2
        with:
          repository: appfair/appfair.github.io.git
          ref: main
          path: appfair.github.io/

      - name: Checkout Casks
        uses: actions/checkout@v2
        with:
          repository: appfair/homebrew-apps
          ref: main
          path: homebrew-apps/
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.



      - name: Test Cask Update
        run: |
          cd homebrew-apps/
          git config credential.username "appfairbot"
          git config credential.password "${{ secrets.APP_FAIR_BOT_TOKEN }}"
          git config user.name "appfairbot"
          git config user.email "appfairbot@appfair.net"
          git pull
          echo '' >> README.md
          git add .
          git commit -m "cask update" || echo "nothing to commit"
          git push

      - name: Clear Casks
        run: |
          rm -rf homebrew-apps/Casks/
          mkdir -p homebrew-apps/Casks/

      - name: Generate Catalog
        run: |
          cd fair/
          swift run -- fairtool catalog --verbose true --hub github.com/appfair --token "${{ secrets.APP_FAIR_BOT_TOKEN }}" --artifact-extension "zip" --cask-folder ../homebrew-apps/Casks/ -o ../appfair.github.io/fairapps.json
          swift run -- fairtool catalog --verbose true --hub github.com/appfair --token "${{ secrets.APP_FAIR_BOT_TOKEN }}" --artifact-extension "ipa" -o ../appfair.github.io/fairapps-iOS.json
          cd ..

      - name: Update Catalog
        run: |
          cd appfair.github.io/
          git config credential.username "appfairbot"
          git config credential.password "${{ secrets.APP_FAIR_BOT_TOKEN }}"
          git config user.name "appfairbot"
          git config user.email "appfairbot@appfair.net"
          git pull 
          git add fairapps.json
          git add fairapps-iOS.json
          git commit -m "catalog update" || echo "nothing to commit"
          git push

          #- name: Update Casks
          #run: |
          #cd homebrew-apps/
          #git config credential.username "appfairbot"
          #git config credential.password "${{ secrets.APP_FAIR_BOT_TOKEN }}"
          #git config user.name "appfairbot"
          #git config user.email "appfairbot@appfair.net"
          #git pull
          #git add .
          #git commit -m "cask update" || echo "nothing to commit"
          #git push

