name: Publish App Fair Catalog

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Catalog
        uses: actions/checkout@v2
        with:
          repository: appfair/appfair.github.io.git
          ref: main
          path: appfair.github.io/

      - uses: fwal/setup-swift@v1
        with:
          swift-version: '5.4'

      - name: Checkout Fair
        uses: actions/checkout@v2
        with:
          repository: appfair/Fair.git
          ref: main
          path: fair/

      - name: Generate catalog
        if: false
        run: |
          cd fair/
          swift run -- fairtool catalog --verbose true --hub github.com/appfair --token "${{ secrets.APP_FAIR_BOT_TOKEN }}" -o ../catalog/fairapps.json
          cd ..

      - name: Update catalog
        env:
          GITHUB_TOKEN: ${{ secrets.APP_FAIR_BOT_TOKEN }}
        run: |
          cd appfair.github.io/
          git config --global user.email "appfairbot@appfair.net"
          git config --global user.name "appfairbot@appfair.net"
          git add fairapps.json
          git commit -m "catalog update" || echo "nothing to commit"
          git push


