name: Publish App Fair Catalog

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Catalog
        uses: actions/checkout@v2
        with:
          repository: appfair/appfair.github.io.git
          ref: main
          path: catalog/


      - name: Test catalog rebuild
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "" >> catalog/fairapps.json
          git config --global user.email "fairapps@appfair.net"
          git config --global user.name "fairapps@appfair.net"

          git -C catalog/ add fairapps.json
          git -C catalog/ commit fairapps.json

      - name: Checkout Fair
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repository: appfair/Fair.git
          ref: main
          path: fair/

      - name: Build catalog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd fair/
          swift run -- fairtool catalog --verbose true --hub github.com/appfair --token "${{ secrets.GITHUB_TOKEN }}" -o ../catalog/fairapps.json
          cd ../catalog/
          git add fairapps.json
          git commit fairapps.json

