##############################################################################
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

name: Publish App Catalogs

env:
  FAIRTOOL: "fairtool"
  # fairtool-head will build from source, which adds a few minutes
  #FAIRTOOL: "fairtool-head"
  
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Homebrew
        if: false
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: "Install ${{ env.FAIRTOOL }}"
        if: false
        run: |
          brew install fair-ground/tool/$FAIRTOOL
          $FAIRTOOL version

      - name: "Configure posting auth"
        run: |
          # configure the posting auth just once
          echo "FAIRTOOL_TWITTER_USER=${{ secrets.APP_FAIR_TWITTER_USER }}" >> $GITHUB_ENV
          echo "FAIRTOOL_TWITTER_CONSUMER_KEY=${{ secrets.APP_FAIR_TWITTER_CONSUMER_KEY }}" >> $GITHUB_ENV
          echo "FAIRTOOL_TWITTER_CONSUMER_SECRET=${{ secrets.APP_FAIR_TWITTER_CONSUMER_SECRET }}" >> $GITHUB_ENV
          echo "FAIRTOOL_TWITTER_TOKEN=${{ secrets.APP_FAIR_TWITTER_TOKEN }}" >> $GITHUB_ENV
          echo "FAIRTOOL_TWITTER_TOKEN_SECRET=${{ secrets.APP_FAIR_TWITTER_TOKEN_SECRET }}" >> $GITHUB_ENV

      - name: Generate macOS catalog
        if: false
        run: |
          cp fairapps-macos.json fairapps-macos_old.json && touch fairapps-macos_old.json
          $FAIRTOOL fair catalog \
            --verbose \
            --hub github.com/appfair \
            --base-repo "App" \
            --funding-sources \
            --token "${{ secrets.APP_FAIR_BOT_TOKEN }}" \
            --catalog-name "Fair Apps" \
            --catalog-identifier "net.appfair.fairapps-macos" \
            --artifact-extension "zip" \
            --fairseal-issuer "appfairbot" \
            --retry-duration 600 \
            --allow-license "${{ secrets.APP_FAIR_ALLOW_LICENSE }}" \
            --allow-name "${{ secrets.APP_FAIR_ALLOW_NAME }}" \
            --deny-name "${{ secrets.APP_FAIR_DENY_NAME }}" \
            --allow-from "${{ secrets.APP_FAIR_ALLOW_FROM }}" \
            --deny-from "${{ secrets.APP_FAIR_DENY_FROM }}" \
            --cask-folder homebrew-app/Casks/ \
            -o fairapps-macos.json

          # update the catalog to generate the markdown and news items 
          $FAIRTOOL source postrelease \
            --from-catalog fairapps-macos_old.json \
            --to-catalog fairapps-macos.json \
            --markdown-index fairapps-macos.md \
            --post-url 'https://appfair.app/fair?app=#(appname_hyphenated)' \
            --tweet-body 'New App Release (macOS): #(appname) #(appversion) - https://appfair.app/fair?app=#(appname_hyphenated)' \
            --post-body 'New Release on the App Fair: #(appname) #(appversion) - https://appfair.app/fair?app=#(appname_hyphenated)' \
            --post-title 'New Release: #(appname) #(appversion)' \
            --post-title-update 'New Release: #(appname) #(appversion)' \
            --post-app-id 'app.#(appname_hyphenated)' \
            --post-caption "#(appname) #(appversion) released" \
            --post-caption-update "#(appname) updated from #(oldappversion) to #(appversion)" \
            --news-items 10 \
            -o fairapps-macos_new.json

          mv fairapps-macos_new.json fairapps-macos.json

      - name: Generate iOS catalog
        if: false
        run: |
          cp fairapps-ios.json fairapps-ios_old.json && touch appcasks_old.json
          $FAIRTOOL fair catalog \
            --verbose \
            --hub github.com/appfair \
            --base-repo "App" \
            --funding-sources \
            --token "${{ secrets.APP_FAIR_BOT_TOKEN }}" \
            --catalog-name "Fair Apps (iOS)" \
            --catalog-identifier "net.appfair.fairapps-ios" \
            --artifact-extension "ipa" \
            --fairseal-issuer "appfairbot" \
            --retry-duration 600 \
            --allow-license "${{ secrets.APP_FAIR_ALLOW_LICENSE }}" \
            --allow-name "${{ secrets.APP_FAIR_ALLOW_NAME }}" \
            --deny-name "${{ secrets.APP_FAIR_DENY_NAME }}" \
            --allow-from "${{ secrets.APP_FAIR_ALLOW_FROM }}" \
            --deny-from "${{ secrets.APP_FAIR_DENY_FROM }}" \
            -o fairapps-ios.json

          # generate AltStore-specific catalog
          cat fairapps-ios.json | jq '.apps |= map(select(.bundleIdentifier|match("${{ secrets.APP_FAIR_ALTSTORE_APPS }}")))' | jq '.sourceURL |= "https://www.appfair.net/fairapps-altstore.json"' > fairapps-altstore.json


          # update the catalog to generate the markdown and news items 
          $FAIRTOOL source postrelease \
            --from-catalog fairapps-ios_old.json \
            --to-catalog fairapps-ios.json \
            --markdown-index fairapps-ios.md \
            --post-url 'https://appfair.app/fair?app=#(appname_hyphenated)' \
            --post-body 'New Release on the App Fair: #(appname) #(appversion) - https://appfair.app/fair?app=#(appname_hyphenated)' \
            --post-title 'New Release: #(appname) #(appversion)' \
            --post-title-update 'New Release: #(appname) #(appversion)' \
            --post-app-id 'app.#(appname_hyphenated)' \
            --post-caption "#(appname) #(appversion) released" \
            --post-caption-update "#(appname) updated from #(oldappversion) to #(appversion)" \
            --news-items 0 \
            -o fairapps-ios_new.json

          mv fairapps-ios_new.json fairapps-ios.json

      - name: Generate appcasks catalog
        if: false
        run: |
          cp appcasks.json appcasks_old.json && touch appcasks_old.json
          $FAIRTOOL brew appcasks \
            --verbose \
            --hub github.com/appfair \
            --base-repo "App" \
            --casks-repo "appcasks" \
            --max-apps 10000 \
            --funding-sources \
            --token "${{ secrets.APP_FAIR_BOT_TOKEN }}" \
            --catalog-name "Homebrew Casks" \
            --catalog-identifier "net.appfair.appcasks" \
            --merge-cask-info "https://formulae.brew.sh/api/cask.json" \
            --merge-cask-stats "https://formulae.brew.sh/api/analytics/cask-install/homebrew-cask/30d.json" \
            --boost-apps "${{ secrets.APP_FAIR_BOOSTED_CASKS }}" \
            --boost-factor 100000 \
            -o appcasks.json

            #--cask-query-count 9 --release-query-count 9 --asset-query-count 9

            #--retry-duration 600 \
            #--starrer-name "appfairbot" \
            #--topic-name "appfair-cask" \

          # update the catalog to generate the markdown and news items 
          $FAIRTOOL source postrelease \
            --from-catalog appcasks_old.json \
            --to-catalog appcasks.json \
            --markdown-index appcasks.md \
            --post-url 'https://appfair.app/fair?cask=#(apptoken)' \
            --tweet-body 'New App Release (macOS): #(appname) #(appversion) - https://appfair.app/fair?cask=#(apptoken)' \
            --post-body 'New Release on the App Fair: #(appname) #(appversion) - https://appfair.app/fair?cask=#(apptoken)' \
            --post-title 'New Release: #(appname) #(appversion)' \
            --post-title-update 'New Release: #(appname) #(appversion)' \
            --post-app-id '#(apptoken)' \
            --post-caption "#(appname) #(appversion) released" \
            --post-caption-update "#(appname) updated from #(oldappversion) to #(appversion)" \
            --update-version-date \
            --news-items 100 \
            -o appcasks_new.json

          mv appcasks_new.json appcasks.json

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2

      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

